CREATE TABLE wfd_recipes (
    recipe_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_owner TEXT DEFAULT '1',
    recipe_name TEXT NOT NULL,
    mealdb_id TEXT DEFAULT NULL,
    recipe_pic TEXT DEFAULT NULL,
    recipe_cuisine TEXT,
    recipe_category TEXT,
    recipe_ingredient_list TEXT[],
    recipe_instructions VARCHAR,
    recipe_tags TEXT[],
    recipe_video TEXT,
    tweaked_original_id TEXT,
    recipe_source TEXT DEFAULT NULL,
    recipe_public BOOLEAN DEFAULT '1'
);

CREATE TABLE wfd_cookbooks (
    cookbook_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cookbook_owner TEXT DEFAULT '1',
    cookbook_name TEXT NOT NULL,
    cookbook_public BOOLEAN DEFAULT '1'
);

CREATE TABLE wfd_cookbookRecipes (
    cookbook_id INTEGER REFERENCES wfd_cookbooks(cookbook_id),
    recipe_id INTEGER REFERENCES wfd_recipes(recipe_id),
    PRIMARY KEY (cookbook_id, recipe_id)
);